import {
  Breadcrumb,
  BreadcrumbHome,
  Breadcrumbs,
  BreadcrumbSeparator,
} from "@/components/breadcrumbs";
import { CopyAnchor } from "@/components/copy-anchor";
import { HighlightMatches } from "@/components/highlight-matches";
import { LessonKeyboardNav } from "@/components/lesson-keyboard-nav";
import { LessonView } from "@/components/lesson-view";
import { NextPageLink } from "@/components/next-page-link";
import { RecordLessonVisit } from "@/components/resume-progress";
import { SidebarLayoutContent } from "@/components/sidebar-layout";
import {
  getAllSections,
  getLesson,
  getLessonContent,
  lessonContentLocale,
  lessonDiskPath,
  lessonUnitPosition,
  lessonUrl,
  numberedLessonTitle,
  sectionShortLabel,
  sectionUrlSlug,
} from "@/data/curriculum";
import { DEFAULT_LOCALE, toLocale } from "@/lib/locales";
import { t, tf } from "@/lib/messages";
import { BASE_PATH } from "@/lib/site";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import fs from "node:fs";
import path from "node:path";

/**
 * The typeset PDF for a lesson, generated by `npm run pdf:lessons` (the
 * Deploy workflow runs it before the build; it is not committed). Presence is
 * checked at build time, so a local build without PDFs simply omits the
 * button. Plain hrefs don't get the basePath added for them.
 */
function lessonPdfUrl(sectionId: string, lessonId: string): string | null {
  const { dir, file } = lessonDiskPath(sectionId, lessonId);
  const rel = `lessons/${dir}/${file}.pdf`;
  if (!fs.existsSync(path.join(process.cwd(), "public", rel))) return null;
  return `${BASE_PATH}/${rel}`;
}

export const dynamicParams = false;

export function generateStaticParams() {
  // Structural (id) enumeration — English source on purpose; the parent
  // [locale] layout's params multiply these across locales.
  return getAllSections(DEFAULT_LOCALE).flatMap((section) =>
    section.lessons.map((lesson) => ({
      section: sectionUrlSlug(section),
      lesson: lesson.id,
    })),
  );
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string; section: string; lesson: string }>;
}): Promise<Metadata> {
  const { locale, section, lesson: lessonId } = await params;
  const lesson = getLesson(toLocale(locale), section, lessonId);

  return {
    title: lesson
      ? `${numberedLessonTitle(lesson.section, lesson)} - ${t(toLocale(locale), "meta.siteTitle")}`
      : t(toLocale(locale), "meta.siteTitle"),
    description: lesson?.description,
  };
}

export default async function Page({
  params,
}: {
  params: Promise<{ locale: string; section: string; lesson: string }>;
}) {
  const {
    locale: rawLocale,
    section: sectionId,
    lesson: lessonId,
  } = await params;
  const locale = toLocale(rawLocale);
  const lesson = getLesson(locale, sectionId, lessonId);

  if (!lesson) {
    notFound();
  }

  const position = lessonUnitPosition(lesson.section, lesson);
  // The page's own locale when a translation exists, else the English
  // transcript (a partial translation always ships).
  const contentLocale = lessonContentLocale(locale, sectionId, lessonId);
  const Content = await getLessonContent(contentLocale, sectionId, lessonId);
  const currentHref = lessonUrl(lesson.section, lesson);

  return (
    <SidebarLayoutContent
      breadcrumbs={
        <Breadcrumbs>
          <BreadcrumbHome />
          <BreadcrumbSeparator className="max-md:hidden" />
          <Breadcrumb
            href={`/#${sectionUrlSlug(lesson.section)}`}
            className="max-md:hidden"
          >
            {sectionShortLabel(lesson.section)}
          </Breadcrumb>
          <BreadcrumbSeparator />
          <Breadcrumb>{numberedLessonTitle(lesson.section, lesson)}</Breadcrumb>
        </Breadcrumbs>
      }
    >
      <RecordLessonVisit
        href={currentHref}
        label={lesson.title ?? numberedLessonTitle(lesson.section, lesson)}
      />
      <LessonKeyboardNav
        prevHref={
          lesson.prev
            ? lessonUrl(lesson.prev.section, lesson.prev.lesson)
            : undefined
        }
        nextHref={
          lesson.next
            ? lessonUrl(lesson.next.section, lesson.next.lesson)
            : undefined
        }
      />
      <div className="mx-auto max-w-7xl">
        <div className="mx-auto max-w-2xl pt-4 pb-10 sm:pt-6 sm:pb-14">
          <div className="w-full">
            <LessonView
              pdfUrl={lessonPdfUrl(sectionId, lessonId)}
              eyebrow={
                <p className="text-sm/7 font-semibold tracking-widest text-gray-500 uppercase dark:text-gray-400">
                  {lesson.unnumbered
                    ? sectionShortLabel(lesson.section)
                    : `${sectionShortLabel(lesson.section)} · ${tf(
                        locale,
                        "lesson.position",
                        {
                          unit: position.unit,
                          n: position.number,
                          total: position.total,
                        },
                      )}`}
                </p>
              }
            >
              <HighlightMatches
                id="content"
                className="prose"
                dep={lesson.id}
                locale={contentLocale}
              >
                <Content />
              </HighlightMatches>
              <CopyAnchor />
            </LessonView>
            <div className="mt-16 border-t border-gray-200 pt-8 dark:border-white/10">
              {lesson.next ? (
                <NextPageLink
                  title={numberedLessonTitle(
                    lesson.next.section,
                    lesson.next.lesson,
                  )}
                  description={lesson.next.lesson.description}
                  href={lessonUrl(lesson.next.section, lesson.next.lesson)}
                />
              ) : (
                <NextPageLink
                  title={t(locale, "end.title")}
                  description={t(locale, "end.description")}
                  href="/"
                />
              )}
            </div>
          </div>
        </div>
      </div>
    </SidebarLayoutContent>
  );
}
